version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: restaurant-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: restaurant-be_app
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:3000" # Adjust according to your app's port
    command: npm run start:prod

volumes:
  pgdata:
